---
title: "Visualization"
author: "James Yang"
date: "6/10/2019"
output: html_document
---

```{r}
library(ggplot2)
```

```{r}
library(readr)
log11 <- read_csv("/Users/james/Downloads/gomoku_models/logfile-11.csv")
log11t <- read_csv("/Users/james/Downloads/gomoku_models/logfile-11t.csv")

win_rate11 <- c(0.7, 0.8, 0.9, 1.0, 0.9, 0.9, 0.9, 0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9, 1.0)
win_rate11t <- c(0.7, 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 0.7, 0.6, 1.0, 1.0, 0.7, 0.6, 0.7, 0.7, 0.8, 0.9, 0.8, 1.0, 0.8, 0.9, 0.5, 0.7, 0.8, 0.8)

# load plot data for transfer learning
ggplot() + geom_line(aes(y = log11t$entropy, x = 1:length(log11t$entropy), color = "transfer")) + geom_line(aes(y = log11$entropy, x = 1:length(log11$entropy), color = "no transfer")) + xlab("Number of games trained") + ylab("Entropy") + theme_minimal() + scale_color_manual("Models", values = c("red", "green"))

ggplot() + geom_line(aes(y = log11t$loss, x = 1:length(log11t$loss), color = "transfer")) + geom_line(aes(y = log11$loss, x = 1:length(log11$loss), color = "no transfer")) + xlab("Number of games trained") + ylab("Loss") + theme_minimal() + scale_color_manual("Models", values = c("red", "green"))

ggplot() + geom_line(aes(y = win_rate11t, x = 1:length(win_rate11t), color = "transfer")) + geom_line(aes(y = win_rate11, x = 1:length(win_rate11), color = "no transfer")) + xlab("Number of games trained") + ylab("Win Rate") + theme_minimal() + scale_color_manual("Models", values = c("red", "green"))
```


